server:
  port: 2333
  address: 0.0.0.0
lavalink:
  plugins:
    - dependency: 'dev.lavalink.youtube:youtube-plugin:1.18.2'
      repository: 'https://maven.lavalink.dev/releases'
    - dependency: 'com.github.topi314.lavasrc:lavasrc-plugin:4.8.3'
      repository: 'https://maven.lavalink.dev/releases'
      snapshot: false
  server:
    password: 'youshallnotpass'
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 10
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
plugins:
  lavasrc:
    providers:
      - 'ytsearch:%QUERY%'
    sources:
      spotify: true
      youtube: true
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
